### ISSUE TITLE
[Design] General architecture, features, and API

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-wallet-service-old#10]
## Introduction

The `hathor-wallet-service` will be used as backend for all official Hathor's wallets.

This issue replaces #1 , so all new design discussions should happen here.

Sync between full node and service is being designed here: PR https://github.com/HathorNetwork/hathor-wallet-service/issues/8.

## Architecture

<pre>
                   +----------------------------------------------------+
                   |                                                    |
                   |                                                    |
┌──────────────┐   |   ┌─────────────────┐       ┌───────────────┐      |
│              │   |   │                 │       │               │      |
│  Full node   │───|──▶│  Tx Processor   │◀─────▶│   Database    │      |
│              │   |   │                 │       │               │      |
└──────────────┘   |   └─────────────────┘       └───────────────┘      |
                   |                                     ▲              |
                   |                                     │              |
                   |                                     ▼              |
                   |                             ┌───────────────┐      |           ┌──────────────┐
                   |                             │               │      |           │              │
                   |                             │  API Service  │◀─────────────────│   Client     │
                   |                             │               │      |           │              │
                   |                             └───────────────┘      |           └──────────────┘
                   |  wallet-service                                    |
                   |                                                    |
                   +----------------------------------------------------+

</pre>

The service will be implemented using AWS services.

- DynamoDB: Database
- AWS Lambda: Tx Processor and API Service
- AWS Gateway API: HTTP and Websocket endpoints
- AWS SQS: Queue service
- AWS Aurora Serverless

#### Tx Processor

Receive transactions/blocks from the full node and update the database. It will receive two types of messages: NEW_TX and UPDATE_TX. The latter is used to notify a change in the tx status (from executed to voided or otherwise).

It must keep the balance and transaction history of all addresses, even the ones not designated for a wallet. In the future, we may include an API to query the address and tx history for any address. We would also easily know the richest addresses.

When a new tx arrives or a tx is updated, it must update the database for all affected wallets.

#### API Service

Load from database and return to the wallet. The idea is to do the least number of calculations here. All things should be pre-computed by the TxProcessor. Only locked balances/authorities may trigger computation on the APIs.

#### Maintenance Tools

For each table, we should have a verification tool that checks its consistency. This tool should also have a parameter to recalculate the records of a given table. These tools will be integrated in our monitoring and alert system.

### Database

Wallet stores the basic status of all wallets that have been created on this service.
```
- Wallet
  - Id
  - XPubKey
  - MaxGap (default: 20)
  - Status (creating, ready, error)
  - CreatedAt
  - ReadyAt
```

WalletBalance contains the balance and authorities for each pair of (walletId, tokenId), separated by locked and unlocked balance/authorities. `TimelockExpires` contains the earliest timestamp at which any locked balance or authority will become unlocked (more on this later).
```
- WalletBalance
  - WalletId
  - TokenId
  - UnlockedBalance
  - LockedBalance
  - UnlockedAuthorities
  - LockedAuthorities
  - TimelockExpires
  - Transactions
```

For each transaction, save the balance of each pair (walletId, tokenId).
```
- WalletTxHistory (for all transactions)
  - WalletId
  - TokenId
  - TxId
  - Balance (positive: received / negative: sent)
  - Timestamp
```

Saves the basic infos of all address seen in the transactions received by this service, even if the corresponding wallet is not created. `Index` indicates the derivation path index used for this address. Both `Index` and `WalletId` will be null until the corresponding wallet is initialized in the service.
```
- Address
  - Address
  - Index
  - WalletId
  - NumberOfTransactions
```

AddressBalance contains the balance and authorities for each pair of (address, tokenId), separated by locked and unlocked balance/authorities. `TimelockExpires` contains the earliest timestamp at which any locked balance or authority will become unlocked (more on this later). Same idea as WalletBalance table.
```
- AddressBalance
  - Address
  - TokenId
  - UnlockedBalance
  - LockedBalance
  - UnlockedAuthorities
  - LockedAuthorities
  - TimelockExpires
  - Transactions
```

For each transaction, save the balance of each pair (address, tokenId). Same idea as WalletTxHistory.
```
- AddressTxHistory
  - Address
  - TxId
  - TokenId
  - Balance (positive: received / negative: sent)
  - Timestamp
```

This table contains all UTXOs as received in the transactions. They are removed as they are spent. `TxProposalId` and `TxProposalIndex` is used when creating/proposing a new tx.
```
- UTXOs
  - TxId
  - Index
  - TokenId
  - Address
  - Value
  - Authorities
  - Timelock: at which time this becomes unlocked
  - Heightlock: at which height this becomes unlocked (for blocks)
  - Locked: boolean indicating if it is locked
  - TxProposalId: the tx proposal id, if applicable
  - TxProposalIndex: the input index on the tx proposal for this UTXO, if applicable
```

Saves info about tx proposals.
```
- TxProposal
  - Id
  - WalletId
  - Status (open, sent, cancelled)
  - CreatedAt
  - UpdatedAt
```

This table is used to store the suggested outputs for a tx proposal. They are stored here until this proposal is either sent or cancelled. The index indicates the output index. For instance, if I create a tx proposal with 5 outputs, there will be 5 entries in this table, with indexes from 0 to 4, with the same `TxProposalId`.
```
- TxProposalOutputs
  - TxProposalId
  - Index
  - Address
  - TokenId
  - Value
  - Timelock
```

Table to store token information, when receiving a TokenCreationTransaction.
```
- Token
  - Id
  - Name
  - Symbol
```

### Unlocking balances and authorities

Both on AddressBalance and WalletBalance we use a best-effort strategy for calculating the locked and unlocked balance and authorities. We save on the database the next lock that expires (`TimestampExpires`). When a client requests the wallet/address balance, in case the current timestamp is past `TimestampExpires`, we compute on demand the new locked and unlocked values before returning, also updating `TimestampExpires` on the corresponding table.

## Flow from wallets

1. Client creates a wallet (`wallet_id = sha256d(pubkey)`).
2. Client polls the wallet until it is ready.
3. Get balance and tx history for a token.
4. Create a tx proposal.
5. Sign the inputs of the tx proposal.
6. Resolve the tx proposal.
7. Propagate the tx proposal.

## Events from Full Node

- New tx or block.
- Update tx or block.

### Authentication

All requests must be signed by `m/1/1` of the wallet's xpriv.

### Websocket:

- Wallet must authenticate once after connection;
- Wallet must received a balance update message every new tx, so it can update its balance and tx history;

### POST `/wallet`: Create a new wallet

* https://github.com/HathorNetwork/hathor-wallet-service/issues/17

When the wallet is created, the following tasks must be executed:
- Mark its addresses in the Address table;
- Calculate the balance of all its tokens and store in the AddressBalance table;
- Create the WalletTxHistory records from the AddressTxHistory;

After requesting the creation of the wallet, the client must do polling to verify when it is ready. It may take a few seconds to be ready. If an error occurs, the user must have the choice to check status again or reset the wallet.

Arguments:
- XPubKey - we expect this xpub to in the account derivation, i.e. from the xpriv you must have derived to `m/44'/280'/0'`.

Returns: `{ walletId, status }`

### GET `/wallet`: Get status of a wallet

Arguments:
- WalletId

Returns: All fields of the wallet, including its status.

### GET `/addresses`: Get wallet's addresses

We can run one query in the Address table filtering by a given `walletId`.

__Open question__: Should we paginate?

Arguments:
- WalletId

Returns:
- List of addresses
  - Address
  - Number of transactions
  - Index

### GET `/balance`: Get wallet's balance

Run one query in the Balance table filtering by `walletId` (and `tokenId` if the argument is passed).

Arguments:
- WalletId
- TokenId (optional)

Returns:
- List of balances:
  - Token `{ Id, Name, Symbol }`
  - Number of transactions
  - Balance `{ Unlocked, Locked }`
  - Authorities `{ unlocked: { mint, melt }, locked: { mint, melt } }`
  - LockExpires

If TokenId is received, it will return only the requested token (list with 1 element).

### GET `/txhistory`: Get wallet's transaction history

* https://github.com/HathorNetwork/hathor-wallet-service/issues/16

Arguments:
- WalletId
- TokenId
- AfterAddress
- Count

Returns:
- AfterAddress
- Count
- List of transactions
  - Format: `{ txId, timestamp, balance }`

### POST `/txproposal`: Create a new tx proposal

When a tx proposal is created, it should mark the used UTXOs. We do this by assigning a TxProposalId and TxProposalIndex to them. So, if a new proposal is created while the old one is still not finalized, the proposal will skip them, avoiding double spending. We can optionally create a scheduled job to cancel all tx proposal opened for more than X minutes.

Arguments:
- Input selection algorithm (optional) (e.g. best match, from highest, from lowest)
- Outputs `[[addr1, amount1, token1, timelock1], [addr2, amount2, token2, timelock2], ...]`
- Inputs (optional) `[[TxId1, Index1], [TxId2, Index2]]`

Returns:
- Tx proposal
  - Id
  - Outputs: `[{ address, value, token, timelock }]`
  - Inputs: `[{ txId, index }]`
  - Tokens: `[tokenId1, tokenId2, etc]`

The wallet can use this info to assemble the tx and mine it, probably using the tx-mining-service, and propagate the tx using the API bellow.

### PUT `/txproposal/{txProposalId}/`: Send the tx

Arguments:
- TxProposalId
- List of input data `[ inputData0, inputData1, ...]` (the signatures)
- List of parents
- TxWeight
- Nonce
- Timestamp

Returns:
- Success or error message

### GET `/txproposal/`: List open txproposals

Arguments:
- WalletId

Returns:
- List of Tx proposals
  - Id
  - Outputs: `[{ address, value, token, timelock }]`
  - Inputs: `[{ txId, index }]`
  - Tokens: `[tokenId1, tokenId2, etc]`

### GET `/txproposal/{txProposalId}/`: Get information about a txProposal

Arguments:
- TxProposalId

Returns:
- Tx proposal
  - Id
  - Outputs: `[{ address, value, token, timelock }]`
  - Inputs: `[{ txId, index }]`
  - Tokens: `[tokenId1, tokenId2, etc]`

### DELETE `/txproposal/{txProposalId}`: Cancel a tx proposal

When a tx proposal is closed, it should remove all locks from the UTXOs used by it.

Arguments:
- TxProposalId

Returns:
- Success or error message

## Open decisions

- **wallet authentication**: old design just said "All requests must be signed by m/1/1 of the wallet's xpriv";
- **wallet sync strategy**: we'll use the websocket as the current wallets? Since everything is pre-computed, maybe just send a message asking the wallet to refresh?;
- **fetch tx API**: we can save the tx on this service, but the current API and UI also show information from the metadata. Would we pass through the request? Maybe we can fetch from the full nodes and also keep a cache;

**Comment by jansegre** [comment]
> PUT /txproposal/{txProposalId}/: Send the tx

I'd drop the last `/` for consistency. But I also think we should accept a trailing `/` on all calls.

**Comment by andreabadesso** [comment]
I'm handling input signatures by deserializing them from base64 strings on  `PUT /txproposal/{txProposalId}/`

7ee0f5857ed21db75f7fd23c25b617e41685416e

This wasn't discussed before but I believe this is the most efficient option

**Comment by andreabadesso** [comment]
We need to discuss how to validate input signatures on the wallet-service `send` API. 

We can't just validate the signature size because if it's multisig, the size may vary.

We could just let it fail on the full-node and store the result

Another possible suggestion would be to be able to configure (as an env variable maybe) a limit for multisig transactions, so if someone needs to send a transaction with multiple signatures, they could setup a custom wallet-service with a higher value

**Comment by obiyankenobi** [comment]
I think the first step is validating the max size a signature can have. If I'm not mistaken, there's a limit.

Apart from that, ideally we should have a method on the lib that validates a transaction "internally". What I mean by that is it should check weight, nonce, inputs/outputs sum and if input data unlocks output script. In other words, should validate everything that doesn't rely on the DAG info, like parents.

**Comment by andreabadesso** [comment]
To be able to validate the tx weight on send requests, I had to query constants from the full-node.

Since lambda functions are stateless, I can't just initialize the hathorLib and store constants in memory, so to avoid a expensive http call to the full node on every sendTx, I am "caching" the data on mysql and invalidating it using a timestamp.

Here is the commit:
https://github.com/HathorNetwork/hathor-wallet-service/commit/40969b0d4c491bee479e1afc58dc3a0e42ec1700

**Comment by andreabadesso** [comment]
On the `POST /tx_proposal` API, when we are asking the wallet-service to select the inputs for me, it would be ideal to return the address derivation index for each input. With this information we can prevent a request from the wallet when it is signing the input.

So I suggest the new response format for the inputs on the create_tx_proposal request to be:

```
{
...,
  "inputs": [
    {
      "txId": "00000039a2ddd5d0f5c0fde6c4e0dcaaa27aaf6696ae0af0d73fc80fe1a807a7",
      "index": 1,
      "addressIndex": 0
    }
  ],
...
}
```

**Comment by obiyankenobi** [comment]
Can't the wallet find out this info locally? From `txId` and `index` of the input, it can get the output script and its associated address. And I imagine we have a way of getting the index from the address.

**Comment by pedroferreira1** [comment]
It's not really easy to get the index from the address and we don't have all generated addresses in the wallet. We could store them but I see no reason to do it.
Besides that, we've discussed of having the full derivation path instead of only the address index, in order to allow any path customization if the user wants to use different accounts with the same seed.
Why do you think it's bad to return this information?

**Comment by obiyankenobi** [comment]
Don't see as a big problem, but wanted to decouple as much as possible. However, I guess it's not really possible with the wallet service.

**Comment by msbrogli** [comment]
Here is my review:

1) Tx Processor: I believe it should be idempotent, i.e., the tx processor leads to the same state when it gets the same transaction two or more times. It is an important behavior for syncing when the service starts.

2) POST `/wallet` needs a lock system to prevent two requests arriving simultaneously.

3) GET `/addresses`: Yes, we should paginate all lists with a variable number of items.

4) GET `/txhistory`: Instead of `skip` and `count`, I'd use `afterAddress` and `count`. When user advances a page, it always receives the next transactions even if new transactions arrive.

5) Isn't it missing a `GET `/txproposal` to retrieve overall info about it (maybe a list)?

6) Open decisions:

6.a) Authentication: We should use a strategy similar to OAuth. The request will have some extra headers (`timestamp`, `nonce`, `signature_method` and `signature`). In this case, we just accept requests with timestamp within a range around current time, and we need to accept only one nonce for a time interval.

6.b) Syncing: We can either receive all txs/blocks from the full node and process them again (or skip the ones that have already been processed) or sync each wallet through their addresses. We need to dive deep more in this matter.

6.c) Fetch TX API: Fetching metadata from a big list of transactions seems slow. I'm not sure whether we should cache them or let the wallet request the metadata from the txs/blocks it needs.

**Comment by andreabadesso** [comment]
> Here is my review:
> 
> 1. Tx Processor: I believe it should be idempotent, i.e., the tx processor leads to the same state when it gets the same transaction two or more times. It is an important behavior for syncing when the service starts.
> 2. POST `/wallet` needs a lock system to prevent two requests arriving simultaneously.
> 3. GET `/addresses`: Yes, we should paginate all lists with a variable number of items.
> 4. GET `/txhistory`: Instead of `skip` and `count`, I'd use `afterAddress` and `count`. When user advances a page, it always receives the next transactions even if new transactions arrive.
> 5. Isn't it missing a `GET `/txproposal` to retrieve overall info about it (maybe a list)?
> 6. Open decisions:
> 
> 6.a) Authentication: We should use a strategy similar to OAuth. The request will have some extra headers (`timestamp`, `nonce`, `signature_method` and `signature`). In this case, we just accept requests with timestamp within a range around current time, and we need to accept only one nonce for a time interval.
> 
> 6.b) Syncing: We can either receive all txs/blocks from the full node and process them again (or skip the ones that have already been processed) or sync each wallet through their addresses. We need to dive deep more in this matter.
> 
> 6.c) Fetch TX API: Fetching metadata from a big list of transactions seems slow. I'm not sure whether we should cache them or let the wallet request the metadata from the txs/blocks it needs.


@msbrogli 

1. I agree. We are currently considering that we will only receive a txid from the bridge once. This should be refactored to guarantee that receiving the same transaction leads to the same state 
2. I agree. We currenlty verify the state of the wallet on the mysql database, but we are vulnerable if two requests arrive simultaneously. I will study what is available for creating a distributed lock on lambda services using our current architecture
3. OK
4. I agree
5. I agree. We should have two different methods, one for retrieving information for a single txproposal (`GET /txproposals/:id`) and another one to retrieve information on all txproposals for the current walletid (`GET /txproposals`).
