### ISSUE TITLE
[Design] Token Actions on tx-proposal

### ISSUE THREAD

**Issue by andreabadesso** [HathorNetwork/hathor-wallet-service-old#14]
# Token Actions

## Create token

A create token action is basically a `Mint Token` action that does not depend on Authority inputs.

* We should validate that the `version` is `2`
```
REGULAR_BLOCK = 0
REGULAR_TRANSACTION = 1
TOKEN_CREATION_TRANSACTION = 2
MERGE_MINED_BLOCK = 3
```
* We should validate if the inputs have enought HTRs to be deposited if the user sent `input` on the `txProposalCreate` request body and fail with `INSUFFICIENT_INPUTS` if invalid.
* `name` and a `symbol` should be sent on the `txProposalSend` request or fail with `MISSING_PARAMETER`
* We should validate if the output has a valid `tokenData` on the `txProposalCreate` request or fail with `INVALID_TOKEN_DATA`:
```
0b10000001: an authority ouput for token with index 1;
0b00000001: a regular output for token with index 1;
0b00000000: a regular output for token with index 0 (HTR);
0b10000000: authority output for HTR - INVALID!
```
* We should validate if the output has a valid `value` on the `txProposalCreate` request or fail with `INVALID_OUTPUT_VALUE`:
```
0b00000001: mint authority
0b00000010: melt authority
0b00000011: melt and mint authorities
```

* If the user sent inputs, but not the full amount needed as a deposit (1% of the quantity of new tokens created), the service needs to automatically select more inputs to fill the gap

### Parameters
`name`[string] - The new token name
`symbol`[string] - The new token symbol
`amount`[number] - The amount of tokens to be created
`destinationAddress`[string] ****[optional]**** - The address to send the newly created tokens
`changeAddress` [string] ****[optional]**** - A change address to change outputs
`createMint` [boolean] ****[optional]**** - Boolean to indicate if we should create a mint authority, defaults to `true`
`createMelt` [boolean] **[optional]** - Boolean to indicate if we should create a melt authority, defaults to `true`
`meltDestination` [string] **[optional]** - The address to send the melt authority
`mintDestination` [string] **[optional]** - The address to send the mint authority

#### `txProposalCreate` Request example:

`POST /txproposals`
```
{
  "id": "cddf7ee73e633e3b72c860e29130899c6aa30fe050ce918a8b30fb7beab6b649",
  "actionType": "create-token",
  "version": 2,
  "name": "Test Token",
  "symbol": "TSTT",
  "amount": 500,
  "changeAddress": "H9Ug2fDV7yyahg7NvmzkZZHejYKfxG8D5M",
  "createMint": true,
  "createMelt": false,
  "meltDestination": "H9Ug2fDV7yyahg7NvmzkZZHejYKfxG8D5M",
  "mintDestination": "H9Ug2fDV7yyahg7NvmzkZZHejYKfxG8D5M",
  "amount": 1000,
  "inputs": [{
    "txId": "00000f98e3f707d9fe389e168b8e412ea5fa651ab74e7464ea1439f4e16e6e87",
    "index": 0
  }]
}
```

#### `txProposalCreate` Response example

```
{
  "success": true,
  "txProposalId": "61201935-238a-40a1-8667-aff184bd7222",
  "inputs": [{
    "txId": "00000f98e3f707d9fe389e168b8e412ea5fa651ab74e7464ea1439f4e16e6e87",
    "index": 0
  }],
  "outputs": [{
    "address": "HLZYjZWnu53DGeoFM4aYgFCnSEhu8e5zR8",
    "value": 5299,
    "tokenData": 0,
  }, {
    "address": "HUVQz3ctv7e8y34LXqDANmnSi1Jhnhs24L",
    "value": 100000,
    "tokenData": 1
  }, {
    "address": "HCLrkUMe8hoYKybDH47XmRpALMKab7AaGa",
    "value": 1,
    "tokenData": 129
  }, {
    "address": "HQsbzfqyk1r8pkEQCdxJXPaqw97d9U7HG9",
    "value": 2,
    "tokenData": 129
  }],
  "changeAddress": "H9Ug2fDV7yyahg7NvmzkZZHejYKfxG8D5M"
}
```

#### `txProposalSend` Request example

`PUT /txproposals/:id`

```
{
    "nonce": 62184,
    "parents": [
      "000005c145a5676068c4f8cc23c3583c0399b733c4a535262c4b97316c47fdd6",
      "000005369c1d3db2ae876b15b7120278de5cb073908f3ff5649df27745aed3dc"
    ],
    "timestamp": 1611607244,
    "weight": 20.94851562403101,
    "inputsSignatures": [
      "RjBEAiBpEA4DkVvLq8lRWxQgdTdpi+psLJvAYSvjOdCepC91KgIgTwP25/pPmDO8F+rsds34+chrDUciJViFg6jlotyTt2UhA7gI0KgR9TLRjim7ORVT6JsBI4TIQrSWL0lSTp/HC0Ca"
    ]
}
```

#### `txProposalSend` Response example
```
{
  "success": true,
  "txProposalId": "6cdb63bc-df2b-46a2-8baf-fbab2cc6c172",
  "txId": "000000337390be8403a7763331acad7ae74d1751eb6a9c602a0636b38f65704a",
  "txHex": "0001010102000005369c1d3db2ae...c0000f2e8"
}
```

## Mint tokens

* We need to validate if there is a mint authority on the inputs (if the user sent inputs).
* We need to validate if the mint authority is of the same token of the output
* We should assert wether the wallet has enough HTR to mint these new tokens. (1% of the newly created tokens.)
* If the user sent inputs, but not the full amount needed as a deposit (1% of the quantity of new tokens minted), the service needs to automatically select more inputs to fill the gap

### Parameters
`amount`[number] - The amount of tokens to be minted
`token` [string] - The token uid that we want to mint
`createAnotherAuthority` [boolean] **[optional]** - Indicates if we should create another mint authority after spending one, defaults to `true`
`destinationAddress`[string] **[optional]** - The address to send the newly created tokens
`changeAddress` [string] **[optional]** - A change address to change outputs (htr)
`authorityAddress` [string] **[optional]** - Address to send the authority if `createAnotherAuthority` is set to `true`

#### `txProposalCreate` Request example:

```
{
  "id": "cddf7ee73e633e3b72c860e29130899c6aa30fe050ce918a8b30fb7beab6b649",
  "actionType": "mint-token",
  "amount": 50,
  "createAnotherAuthority": true,
  "changeAddress": "H9Ug2fDV7yyahg7NvmzkZZHejYKfxG8D5M",
  "authorityAddress": "H9Ug2fDV7yyahg7NvmzkZZHejYKfxG8D5M",
  "inputs": [{
    "txId": "000003ac2284301db845a1a03fa67d27f6f8d9234e475bde04606fa42a522b10",
    "index": 0
  }, {
    "txId": "000001768f32d54599f1470f5c92f075063b7bd00075e3dca076d5b1d718c1c2",
    "index": 2, // This is the index of the mint authority utxo on this transaction
  }]
}
```

#### `txProposalSend` Request example

`PUT /txproposals/:id`

```
{
    "nonce": 62184,
    "parents": [
      "000005c145a5676068c4f8cc23c3583c0399b733c4a535262c4b97316c47fdd6",
      "000005369c1d3db2ae876b15b7120278de5cb073908f3ff5649df27745aed3dc"
    ],
    "timestamp": 1611607244,
    "weight": 20.94851562403101,
    "inputsSignatures": [
      "RjBEAiBpEA4DkVvLq8lRWxQgdTdpi+psLJvAYSvjOdCepC91KgIgTwP25/pPmDO8F+rsds34+chrDUciJViFg6jlotyTt2UhA7gI0KgR9TLRjim7ORVT6JsBI4TIQrSWL0lSTp/HC0Ca",
      "RjBEAiBpEA4DkVvLq8lRWxQgdTdpi+psLJvAYSvjOdCepC91KgIgTwP25/pPmDO8F+rsds34+chrDUciJViFg6jlotyTt2UhA7gI0KgR9TLRjim7ORVT6JsBI4TIQrSWL0lSTp/HC0Ca",
    ]
}
```

#### `txProposalSend` Response example
```
{
  "success": true,
  "txProposalId": "6cdb63bc-df2b-46a2-8baf-fbab2cc6c172",
  "txId": "000000337390be8403a7763331acad7ae74d1751eb6a9c602a0636b38f65704a",
  "txHex": "0001010102000005369c1d3db2ae...c0000f2e8"
}
```

## Melt tokens

* We need to validate if there is a melt authority on the inputs
* We need to validate if the melt authority is of the same token of the output
* We should validate if the newly created HTR on the output is equal to the number of melted tokens divided by 100 (1%)
* If the user sent inputs, but the value of their sum is lower than the amount specified for the token, the service needs to automatically select more inputs to fill the gap

### Parameters
`amount`[number] - The amount of tokens to be created
`createAnotherAuthority` [boolean] **[optional]** - Indicates if we should create another melt authority, defaults to `true`
`destinationAddress`[string] **[optional]** - The address to send the newly created tokens
`authorityAddress` [string] **[optional]** - Address to send the authority if `createAnotherAuthority` is set to `true`

#### `txProposalCreate` Request example:

```
{
  "actionType": "melt-token",
  "amount": 50,
  "createAnotherAuthority": true,
  "authorityAddress": "HS8gSuHPVysR9KkeEH7jzDrwP6F8Zk8euM",
  "destinationAddress": "HS8gSuHPVysR9KkeEH7jzDrwP6F8Zk8euM",
  "inputs": [{
    "txId": "000001768f32d54599f1470f5c92f075063b7bd00075e3dca076d5b1d718c1c2",
    "index": 3
  }, {
    "txId": "0000075fc0c99977a9cff30936d9beb5f4b71c243ddaa692b31f961caec23b41",
    "index": 1,
  }]
}
```

## Delegate Authority

* If the user did not send the inputs, we need to validate if he sent the quantity to be delegated
* If ther user sent the inputs, we should validate if the quantity of authorities in the inputs is >= quantity. If it is not, we should automatically select the missing input quantity

### Parameters
`createAnotherAuthority` [boolean] **[optional]** - Indicates if we should create another mint/melt authority, defaults to `true`
`destinationAddress`[string] - The address to send the delegated authorities
`quantity` [number] - The number of authorities to delegate

#### `txProposalCreate` Request example:

```
{
  "actionType": "delegate-mint", // or "delegate-melt"
  "quantity": 2,
  "createAnotherAuthority": true,
  "changeAddress": "H9Ug2fDV7yyahg7NvmzkZZHejYKfxG8D5M",
  "destinationAddress": "H9Ug2fDV7yyahg7NvmzkZZHejYKfxG8D5M",
  "inputs": [{
    "txId": "0000075fc0c99977a9cff30936d9beb5f4b71c243ddaa692b31f961caec23b41",
    "index": 2
  }]
}
```

## Destroy Authority

* If the user did not send the inputs, we need to validate if he sent the quantity to be destroyed
* If the user sent the inputs, we should validate if the quantity of authorities in the inputs is >= quantity
* If the user sent the inputs, we should validate if all the inputs are from the same token he wants to destroy
* If the user sent the inputs and the quantity, we should validate if the the sum of inputs is >= quantity

- [ ] We are currently validating if outputs are empty on `txProposalCreate`, we need to refactor this to accept empty outputs.

### Parameters
`quantity` [number] - Quantity of authorities to destroy
`token` [string] - Token uid

#### `txProposalCreate` Request example:

```
{
  "actionType": "destroy-mint", // or "destroy-melt"
  "quantity": 1,
  "token": "000001768f32d54599f1470f5c92f075063b7bd00075e3dca076d5b1d718c1c2",
  "inputs": [{
    "txId": "00003886c22ac0f96070573c489b8a127d16aa78c7e03f194cad63ded45e007d",
    "index": 0
  }]
}
```

# Changes needed and observations

- [ ] We need to store `tokenData` on `tx_proposal_outputs` table to be able to use it on  `txProposalSend` .
- [ ] We are considering that the API will already be using the refactored format for `txProposalCreate`:
- [ ] We need to return the txId of the transaction on `txProposalSend`

```
{
  inputs: [{
    txId,
    index
  }],
  outputs: [{
    address,
    amount,
    token,
    timelock?,
    tokenData?
  }],
  version?,
}
```

# Estimated work time

I estimate **one week** to develop and test this feature.

**Comment by pedroferreira1** [comment]
I like the design, especially the request/response and the error handling descriptions. I just think the wallet-service could do a bit more, I am not sure about the first ideas of the service responsibilities but especially with the inputs I think it should be able to handle all of them automatically.

1. The wallet won't be able to automatically select the inputs for the transactions. So I believe we shouldn't expect the inputs as a required field, only as optional if the user knows the inputs to spend. I think the wallet-service should always automatically select the inputs by default using the algorithm of choice in case of a regular transaction.
2. I think we should have a type in the tx-proposal request to specify the transaction type the user wants to create (e.g. create_token, regular_tx, mint, melt, delegate_mint, destroy_mint, ...). For each type we have expected parameters and a different validation method. (i) Create token requires name, symbol, amount, destination address (optional), change address (optional) and if wants mint/melt authorities (with default to create two outputs with both authorities). (ii) Regular transaction is what is already implemented. (iii) Mint requires amount, if will create another mint authority (default to yes), destination address (optional) and HTR change address (optional). (iv) Melt requires amount, if will create another melt authority (default to yes) and HTR destination address (optional). (v) Delegate requires destination address and if will create another authority (default to yes). (vi) Destroy requires quantity. I think all of them should have an optional parameter to send the input but if not sent should automatically select, e.g. the mint should automatically select the mint utxo and the HTR utxo to spend as deposit. This is a suggestion but this gives much more responsibilities to the wallet-service, which I think should be but open for discussion.
3. This has nothing to do with this specific design but given what we've been seeing in all use cases I think we should expect always a change address optional parameter in all tx-proposals, even in the regular tx.
4. I like this part: "We need to return the txId of the transaction on txProposalSend". It's required to know the token UID when creating a token to build the configuration string.

**Comment by msbrogli** [comment]
I also like the design. I feel @pedroferreira1 covered my thoughts. I agree with @pedroferreira1's point (2) in regards to adding a type to each tx-proposal. I also think that's important to allow users to control the change address.

I still don't get why we would need to receive the inputs from the client. But I don't see it as a bad thing. Indeed, if the client would like to set the inputs (or part of them), we should allow them to do so. After all, it's their transaction, right?

**Comment by andreabadesso** [comment]
@pedroferreira1 @msbrogli 

I agree with all the points and updated the design with those changes.

**Comment by pedroferreira1** [comment]
Some comments about the new design

1. Create token: I didn't understand the request example. The user must send the authorities outputs with the correct value and tokenData? And the change output as well? For me the user should send only the amount and address and you would create all outputs.
2. Create token: should we have two parameters to set the destination address of the mint/melt authorities?
3. Create token: we are mixing camelCase (txId, tokenData) with snake_case (create_mint, change_address). Should we keep only one type?
4. Mint: the same comment as the create-token. Should we expect the full array of outputs? Maybe we add a "token" parameter and we can create the outputs.
5. Mint: when you receive the array of inputs do you expect it 100% ready? Or the user could send you the mint authority to spend and you select the HTR utxo to deposit? (I believe that we can expect the full array of inputs but this should be clear in the design)
6. Melt: the same as comments 4 and 5 for mint. If we change there, we must change here.
7. Delegate: the same as comment 4.
8. Delegate: can we have the `destination_address` as optional? I believe it should be required. Besides that, maybe we could have an optional address to send the `create_another` authority to you.
9. Destroy: if the user sends the inputs, you must validate that all inputs are from the token he also sent.

**Comment by andreabadesso** [comment]
1. I agree. I left the outputs from the previous suggestion. Updated
2. I can't see a reason not to. Updated
3. I agree. Fixed
4. I agree. Updated
5. That's a valid point. I think we should allow the user to partially send the inputs, e.g: send the authority but not the htrs to be deposited
6. Done
7. Done
8. I agree. Fixed
9. I agree. Added the remark

**Comment by pedroferreira1** [comment]
For me the design is good. Just some small comments but nothing critical.

1. We should make it clear in the design (in each action) if we expect the full array of inputs. Right now for example, in our running code, if we receive the inputs, we expect the `sumInputs >= sumOutputs`, we don't automatically select more inputs to complete a tx if one is sent.
2. Create token and destroy authority request example have an `outputs: []`. Maybe we should remove it, it looks like we have to send it in the request.
3. In all `createAnother` parameters maybe we should rename to `createAnotherAuthority`, what do you think?
4. In mint, melt and delegate maybe we could add a `authorityAddress` as optional, for the user to select the destination address of the authority in case of `createAnotherAuthority = true`.

**Comment by andreabadesso** [comment]
@pedroferreira1 

1. I agree. Done.
2. I agree. Done.
3. I also agree. Done.
4. Done!

**Comment by pedroferreira1** [comment]
Approved.

**Comment by msbrogli** [comment]
@andreabadesso Approved. I don't feel it is clear what are the parameters of each endpoint and which of them are optional. The examples are really useful but they don't clarify which ones are optional.

**Comment by andreabadesso** [comment]
> @andreabadesso Approved. I don't feel it is clear what are the parameters of each endpoint and which of them are optional. The examples are really useful but they don't clarify which ones are optional.

@msbrogli We have a "Parameters" section for each API indicating which parameters are optional. I've just updated the issue making the headings clearer and added **bold** to the optional fields

**Comment by msbrogli** [comment]
@andreabadesso That's great. Thanks!
