### ISSUE TITLE
incident: reorg failed on 04/16/2022

### ISSUE THREAD

**Issue by andreabadesso** [HathorNetwork/hathor-wallet-service-old#205]
## Summary

The wallet-service daemon sync stopped at `2022-04-16T10:33:17.111Z` after a re-org failure. The last log messages from CloudWatch are:

```
2022-04-16T10:33:21.382Z 957548bd-114b-4728-be46-0b299c1d4bff INFO Handling reorg. Our latest valid block is 2385303 and our highest block height is 2385304
2022-04-16T10:33:21.408Z 957548bd-114b-4728-be46-0b299c1d4bff INFO Setting 1 transactions as voided.
2022-04-16T10:33:21.415Z 957548bd-114b-4728-be46-0b299c1d4bff INFO Setting WalletTxHistory as voided from 1 transactions.
2022-04-16T10:33:21.462Z 957548bd-114b-4728-be46-0b299c1d4bff INFO Setting AddressTxHistory as voided from 1 transactions.
2022-04-16T10:33:21.476Z 957548bd-114b-4728-be46-0b299c1d4bff INFO Setting 1 tx_outputs as voided.
2022-04-16T10:33:21.487Z 957548bd-114b-4728-be46-0b299c1d4bff INFO Rebuilding balances for 1 addresses.
957548bd-114b-4728-be46-0b299c1d4bff	INFO	Errored on onHandleReorgRequest:  AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 743457871
- 743456680
       ^
    at y (/var/task/src/webpack:/src/commons.ts:453:12)
    at process.addresses (internal/process/task_queues.js:97:5)
    at m (/var/task/src/webpack:/src/commons.ts:520:50)
    at Runtime.h [as handler] (/var/task/src/webpack:/src/txProcessor.ts:149:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 743457871,
  expected: 743456680,
  operator: 'strictEqual'
}
```

I've removed all `userIds` from unleash so all users should be on the old facade until this problem is fixed

## Logs

- [onHandleReorgRequest](https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fhathor-wallet-service-mainnet-onHandleReorgRequest/log-events/2022$252F04$252F16$252F$255B$2524LATEST$255De39c54650625440690c904b69de8b5e7)

#### Why?

When we detect a reorg, the `onHandleReorg` lambda finds the affected balances and after removing the affected transactions and their `tx_outputs`, rebuilds the balances

There are several assertions that are done in this process and one of them calculates if the `address_balance` table matches the sum of the values on the `address_tx_history` table, this assertion failed

#### Why?

Those are the queries that were done to fetch the `address_balance` and `address_tx_history`:

`fetchAddressBalance`
```sql
SELECT *
       FROM `address_balance`
      WHERE `address` IN ('HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt')
   ORDER BY `address`, `token_id`;
```
| address | token_id | locked_balance | unlocked_balance | unlocked_authorities | locked_authorities | timelock_expires | transactions |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
|HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt|00                                                              |205071|743252800|0  |0  |NULL|323086|
|HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt|00000000dd500f65bf2c4982ef1a65f3291ba9dc678965a0caade207e15664c4|200   |0        |0  |0  |0   |1     |

`fetchAddressTxHistorySum`

```sql
SELECT address,
            token_id,
            SUM(`balance`) AS balance,
            COUNT(`tx_id`) AS transactions
       FROM `address_tx_history`
      WHERE `address` IN ('
')
        AND `voided` = FALSE
   GROUP BY address, token_id
   ORDER BY address, token_id;
```
| address | token_id | balance | transactions |
| :----: | :----: | :----: | :----: |
|HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt|00                                                              |743456680|532645|
|HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt|00000000dd500f65bf2c4982ef1a65f3291ba9dc678965a0caade207e15664c4|200      |1     |

Those are the assertions that are done to compare those two tables:

```javascript
    assert.strictEqual(addressBalance.tokenId, addressTxHistorySum.tokenId);
    assert.strictEqual(addressBalance.unlockedBalance + addressBalance.lockedBalance, addressTxHistorySum.balance);
```

The first assertion successfully passes, and the second one fails for the Hathor token (00) as we can see on the error log.

Checking manually, we can see why:

`addressBalance.unlockedBalance` `(205071)` + `addressBalance.lockedBalance` `(743252800)` = `743457871`
`addressTxHistorySum.balance` = `743456680`
`743456680 != 743457871`

A difference of 1191, or 11.91 HTR

#### Why?

I searched for the last reorg and it was for the same address (`HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt`), 2 hours earlier:

```
2022-04-16T08:20:01.933Z 631cf30e-2caa-4e07-83eb-4959963bd116 INFO Handling reorg. Our latest valid block is 2385040 and our highest block height is 2385041
2022-04-16T08:20:01.981Z 631cf30e-2caa-4e07-83eb-4959963bd116 INFO Removing transactions [ '0000000000000000033f107fc32d597e5f447be375f703b9af04fbe9284ea86a' ]
2022-04-16T08:20:01.982Z 631cf30e-2caa-4e07-83eb-4959963bd116 INFO Setting 1 transactions as voided.
2022-04-16T08:20:02.002Z 631cf30e-2caa-4e07-83eb-4959963bd116 INFO Setting WalletTxHistory as voided from 1 transactions.
2022-04-16T08:20:02.024Z 631cf30e-2caa-4e07-83eb-4959963bd116 INFO Setting AddressTxHistory as voided from 1 transactions.
2022-04-16T08:20:02.041Z 631cf30e-2caa-4e07-83eb-4959963bd116 INFO Setting 1 tx_outputs as voided.
2022-04-16T08:20:02.073Z 631cf30e-2caa-4e07-83eb-4959963bd116 INFO Rebuilding balances for 1 addresses.
2022-04-16T08:20:55.563Z 631cf30e-2caa-4e07-83eb-4959963bd116 INFO Reorg is done.
END RequestId: 631cf30e-2caa-4e07-83eb-4959963bd116
```

As we can see, the re-org was successful, so the problem was caused by something in between the blocks `2385040` and `2385303`

#### Why?

I searched the database for transactions with 1191 as value between that range and [found this transaction](https://explorer.hathor.network/transaction/000000009752b6f211c9e5b0968d1c859696bd6006d193d5d27f6430475ba17f)

We have this transaction on our database, both on `transaction` table and on the `address_tx_history` table but apparently, the `tx_output` and balance calculation was not done properly when the transaction that spends the `11.91` HTR utxo arrived on the `onNewTxRequest` lambda.

[This is the transaction](https://explorer.hathor.network/transaction/000012ba16de1caaee3ad549165ef4f7d8598a39d87a7b8611683dcd38e31f29) that spends the 11.91 HTR utxo.

We also have this transaction on our database, so that means that it was processed by the `onNewTxRequest`

Since we don't have logs on that lambda, it is hard to figure out what happened but from reading the code, the only possible way that this might have happened is if the transaction came from the fullnode with no inputs, as it would pass by [this line](https://github.com/HathorNetwork/hathor-wallet-service/blob/cf83c36ec52c00004e05063fa244316157434f50/src/txProcessor.ts#L277) with no errors and also won't subtract from the address balance on the next two lines

## Short-term solution

I suggest we fix the database information instead of doing a full re-sync, we can do that by setting the `11.91` HTR `tx_output` to spent:

```sql
UPDATE tx_output
   SET spent_by = '000012ba16de1caaee3ad549165ef4f7d8598a39d87a7b8611683dcd38e31f29'
 WHERE tx_id = '000000009752b6f211c9e5b0968d1c859696bd6006d193d5d27f6430475ba17f'
   AND index = 1;
```

We also need to update the `address_balance` table for the affected address:

```sql
UPDATE address_balance
   SET balance = balance - 1191
 WHERE address = 'HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt'
   AND token_id = '00';
```

I also suggest we add more logs to the `onNewTxRequest` to be able to properly debug this type of error, as we were not able to figure out the root cause of the problem.

#### Missing utxos

I ran a script to verify all transactions on the `address_tx_history` to check if our database is valid

Apparently, there are 497 transactions that were voided on that list that does not exist in our database

Digging deeper, It turns out that the short-term solution that I gave to [this error](https://github.com/HathorNetwork/hathor-wallet-service/issues/192) was wrong, I should have set those rows to `voided` instead of deleting them

This will cause this specific user to have incorrect transaction history as the voided transactions won't show up.

#### Wrong transaction count on the `address_balance` table
 
The total number of transactions for the address `HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt` is different from the `address_balance` table and the count of transactions on the `address_tx_history` table, this needs to be investigated in another issue as it does not appear to be related to this specific incident

**Comment by pedroferreira1** [comment]
address | token_id | balance | transactions
-- | -- | -- | --
HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt | 00 | 743456680 | 532645
HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt | 00000000dd500f65bf2c4982ef1a65f3291ba9dc678965a0caade207e15664c4 | 200 | 1

Is this table correct? Or the locked value is in the unlocked column?

I don't see any reasons why the transaction would arrive without inputs, I think we should try to reproduce the same error.

Is it possible to get a snapshot before the error happened and sync from that moment? So we can see if we can reproduce and debug this error?
