### ISSUE TITLE
incident: sync stopped on 18/05/2022

### ISSUE THREAD

**Issue by andreabadesso** [HathorNetwork/hathor-wallet-service-old#227]
Sync failed when trying to send transaction `000000008cd231281dc44c7c7ba8acc4da95848211bb6ba6cd67e45b538fa87f`

### Why?

Checking the `onNewTxRequest` logs, we had an assertion error while trying to mark the transaction inputs as spent:

```
Errored on onNewTxRequest:  Expected values to be strictly equal: 0 !== 1
```

This assertion is done on the `updateTxOutputSpentBy` method, after the query to update the `spent_by` column of the `tx_output` table to validate that the number of affected `tx_outputs` is equal to the inputs that were sent as a parameter to the method:

```typescript
    const result: OkPacket = await mysql.query(
      `UPDATE \`tx_output\` USE INDEX (PRIMARY)
          SET \`spent_by\` = ?
        WHERE (\`tx_id\` ,\`index\`)
           IN (?)`,
      [txId, entries],
    );

    assert.strictEqual(result.affectedRows, inputs.length);
```

### Why?

I checked the transaction [on the explorer ](https://explorer.hathor.network/transaction/000000008cd231281dc44c7c7ba8acc4da95848211bb6ba6cd67e45b538fa87f) to get the inputs it was trying to use and there was only one input, from [this transaction](0000000090db1a72b14d7af871f72345689de27739bc374e44f724ba3d121146).

I queried the wallet-service database and the we did not have this transaction stored

### Why?

We have two mechanisms of sending transactions to the wallet-service, the `block sync` and the `mempool sync`. This incident happened during a complete re-sync of the database, so we know that the issue happened during the `block sync` mechanism

The way it works is by downloading block by block in series and the transactions that each block directly confirm by [downloading the dag of transactions starting from the parents](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/blob/041dd8f5ff0126790009c1e9f45cab5254123f80/src/utils.ts#L495)

The problem with this transaction is that it is confirmed by the block with height `1727402` and uses funds from a transaction that is confirmed by a [block](00000000000000003902ef2592e5d30712c4b249f1eb5623360fc9cd8dfa54b3) with height `1727403`

Since the algorithm was traversing the DAG of transactions using only the list of parents, there were always a possibility that we missed a transaction dependency, causing the error.

## Solution

We should get not only the transactions that have the block we are downloading as `first_block` but also the input tree for that transaction, ignoring transactions that were confirmed by previous blocks

This is done on [this PR](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/46)

**Comment by pedroferreira1** [comment]
✅

**Comment by msbrogli** [comment]
@andreabadesso On the last "why", I feel you should explicitly explain that the syncer was traversing the DAG using only the parents. The fix consists into using the inputs as well.

Besides this point, it's approved for me.

**Comment by andreabadesso** [comment]
@msbrogli Updated the last "Why" stating explicitly that we were using only the parents DAG

**Comment by msbrogli** [comment]
It's approved for me.
