### ISSUE TITLE
incident: locked balances are broken for some miners on the address_balance feature on the explorer

### ISSUE THREAD

**Issue by andreabadesso** [HathorNetwork/hathor-wallet-service-old#237]
After deploying the `address_balance` feature to `mainnet`, we've noticed that some addresses had big values for the `locked_balance` amount

### Why?

Checking the `address_balance` table for one of the addresses (`HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt`), I've noticed that indeed the `locked_balance` column value for the hathor token was very big:

![Screen Shot 2022-07-07 at 12 05 59](https://user-images.githubusercontent.com/3586068/177807193-ed1de600-6e0b-4c23-be93-e237eb8e3f14.png)

So at first, my suspicion was the `unlockUtxos` method that is called on every block that is received

### Why?

The mechanism to unlock utxos and re-calculate the `address_balance` table row for each address token_id is by detecting what utxos were locked at a given block height when it is received through the sync mechanism and subtract those utxos values from the `locked_balance` column 

After checking the code and the `address_balance` table for other addresses, I've excluded that possibility as we would have other miners with the same problem

So finally, I realized that the `locked_balance` is also changed when a re-org happens, on the [`rebuildAddressBalancesFromUtxos`](https://github.com/HathorNetwork/hathor-wallet-service/blob/43a94f151891e85d9eeed023fade772f6b110f77/src/db/index.ts#L2007) method called from the `handleReorg` algorithm

### Why?

As we can see [on this query](https://github.com/HathorNetwork/hathor-wallet-service/blob/43a94f151891e85d9eeed023fade772f6b110f77/src/db/index.ts#L2049), while rebuilding the `address_balance`'s `locked_balance` column, we only checked if the `heightlock` or `timelock` field was different from `NULL`, we ignored the fact that the utxo might have already been unlocked in the past:

```sql
    INSERT INTO \`address_balance\` (
      \`address\`,
      \`token_id\`,
      \`unlocked_balance\`,
      \`locked_balance\`,
      \`locked_authorities\`,
      \`timelock_expires\`,
      \`transactions\`
    )
       SELECT address,
              token_id,
              0 AS unlocked_balance,
              SUM(\`value\`) AS locked_balance,
              BIT_OR(\`authorities\`) AS locked_authorities,
              MIN(\`timelock\`) AS timelock_expires,
              COUNT(DISTINCT \`tx_id\`) -- transactions
         FROM \`tx_output\`
        WHERE (\`heightlock\` IS NOT NULL
           OR \`timelock\` IS NOT NULL)
          AND spent_by IS NULL
          AND voided = FALSE
          AND address IN (?)
     GROUP BY \`address\`, \`token_id\`
   ON DUPLICATE KEY UPDATE
    locked_balance = VALUES(locked_balance),
    locked_authorities = VALUES(locked_authorities),
    timelock_expires = VALUES(timelock_expires),
    transactions = transactions + VALUES(\`transactions\`)
```

So on every reorg, we are calculating the wrong value for `locked_balance` for all addresses that were involved in that re-org

## Solution

We should add a `AND locked = TRUE` clause on the `locked_balance` query and a `AND locked = FALSE` clause on the `unlocked_balance` rebuild query

This is done on [this PR](https://github.com/HathorNetwork/hathor-wallet-service/pull/236)

## Fix for the broken wallet-service database

Our current wallet-service database is broken, because the affected addresses have wrong values for both `locked_balance` and `unlocked_balance`

To avoid a complete re-sync of the wallet-service instance, we can do the same query that is done on the `rebuildAddressBalance` method manually, after pausing the sync daemon (to make sure that no blocks or transactions will be missed) and after https://github.com/HathorNetwork/hathor-wallet-service/pull/236/ is merged

This is the suggested query:
```sql
    BEGIN TRANSACTION;

    DELETE
      FROM `address_balance`
     WHERE `address` IN (SELECT address FROM address_balance WHERE locked_balance > 0);

    INSERT INTO address_balance (
      `address`,
      `token_id`,
      `unlocked_balance`,
      `locked_balance`,
      `unlocked_authorities`,
      `locked_authorities`,
      `timelock_expires`,
      `transactions`
    )
     SELECT address,
            token_id,
            SUM(`value`), -- unlocked_balance
            0,
            BIT_OR(`authorities`), -- unlocked_authorities
            0, -- locked_authorities
            0, -- timelock_expires
            COUNT(DISTINCT `tx_id`) -- transactions
       FROM `tx_output`
      WHERE spent_by IS NULL
        AND voided = FALSE
        AND locked = FALSE
        AND address IN (SELECT address FROM address_balance WHERE locked_balance > 0)
   GROUP BY address, token_id

    INSERT INTO `address_balance` (
      `address`,
      `token_id`,
      `unlocked_balance`,
      `locked_balance`,
      `locked_authorities`,
      `timelock_expires`,
      `transactions`
    )
       SELECT address,
              token_id,
              0 AS unlocked_balance,
              SUM(`value`) AS locked_balance,
              BIT_OR(`authorities`) AS locked_authorities,
              MIN(`timelock`) AS timelock_expires,
              COUNT(DISTINCT `tx_id`) -- transactions
         FROM `tx_output`
        WHERE spent_by IS NULL
          AND voided = FALSE
          AND locked = TRUE
          AND address IN (SELECT address FROM address_balance WHERE locked_balance > 0)
     GROUP BY `address`, `token_id`
   ON DUPLICATE KEY UPDATE
    locked_balance = VALUES(locked_balance),
    locked_authorities = VALUES(locked_authorities),
    timelock_expires = VALUES(timelock_expires),
    transactions = transactions + VALUES(`transactions`)

    -- COMMIT;
```

This should automatically recalculate (and fix) balances for all `address_balance` rows that have locked balances

## Fix for the Logstash stored data

Since we are updating the database directly, we also need to force Logstash to fetch data again for the affected balances

I suggest removing the file that holds state for the last timestamp fetched on the logstash task for address_balances so it will fetch the whole database again, fixing the broken records

**Comment by lucas3003** [comment]
The solution looks good to me. I think we need to inform the oncall, because these steps potentially can trigger alarms.

**Comment by luislhl** [comment]
> after pausing the sync daemon

How will you pause it? If you plan on manually changing the number of pods in the deployment to 0 temporarily, don't forget to pause the Flux sync as well on them, otherwise Flux will undo any manual change made in Kubernetes.

---

Apart from the detail above, for me this is :heavy_check_mark:

**Comment by andreabadesso** [comment]
This solution was applied properly last week and the wallet-service is already synced, we did not have to run the `Fix for the Logstash stored data` step as running the query updated the `updated_at` column for all affected rows, forcing the logstash task to update them to the correct values
