### ISSUE TITLE
[Design] fix the token database with the correct values for transactions

### ISSUE THREAD

**Issue by andreabadesso** [HathorNetwork/hathor-wallet-service-old#280]
## Motivation

After https://github.com/HathorNetwork/hathor-wallet-service/pull/273 was merged, we need a mechanism to fix the current `mainnet` database without having to re-sync the entire database

## Guide-level explanation

We can get the number of transactions for each token by looking at the `tx_output` table that contains all transaction outputs (spent or not) ever made on the blockchain

Before we update the `token` table with those values, we need to pause the wallet-service sync to prevent new blocks and transactions from being missed from the calculation

## Reference-level explanation

This is exactly the query that will be ran on the `dev-testnet`, `testnet` and `mainnet` databases (after the sync is paused):

```sql
 INSERT INTO token (`id`, `transactions`)
 		  SELECT token_id AS id,
 		         COUNT(DISTINCT(tx_id)) AS transactions
 		    FROM `tx_output`
 		GROUP BY token_id
ON DUPLICATE KEY UPDATE `transactions` = VALUES(`transactions`),
                        `updated_at` = (SELECT CURRENT_TIMESTAMP());
```

---
Reviewers: @pedroferreira1 @luislhl

**Comment by pedroferreira1** [comment]
✅

**Comment by luislhl** [comment]
:white_check_mark:
