### ISSUE TITLE
chore: make the deploy fail when an error is found on the deploy

### ISSUE THREAD

**Issue by andreabadesso** [HathorNetwork/hathor-wallet-service-old#291]
More details on https://github.com/HathorNetwork/on-call-incidents/issues/65

**Comment by luislhl** [comment]
I've tried reproducing this after the changes in https://github.com/HathorNetwork/hathor-wallet-service/pull/409, but I couldn't.

My test consisted of creating a wrong migration like the one below, and running the build:

```js
'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.removeColumn('push_devices', 'wefwefwef');
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.removeColumn('push_devices', 'wefwefwef');
  }
};
```

It just errored out with `ERROR: Can't DROP 'wefwefwef'; check that column/key exists` and stopped the build, like expected.

So I would say we could close this issue already.

This is the link to the build logs: https://eu-central-1.console.aws.amazon.com/codesuite/codebuild/769498303037/projects/hathor-wallet-service/build/hathor-wallet-service%3A4e8241bc-6baf-44b7-ab30-cbd418e3c4f6/?region=eu-central-1

**Comment by luislhl** [comment]
Reviewers @andreabadesso and @alexruzenhack

**Comment by andreabadesso** [comment]
Oh! This was fixed in https://github.com/HathorNetwork/hathor-wallet-service/pull/293, I forgot to close this issue, sorry!

Approved

**Comment by alexruzenhack** [comment]
Ack.
