### ISSUE TITLE
Return addressIndex in create tx proposal POST

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-service-old#43]
This change was suggested here https://github.com/HathorNetwork/hathor-wallet-service/issues/10#issuecomment-763236110 and it's needed for the lib integration.

**Comment by jansegre** [comment]
Is it worth expanding this to return the derivation path? Or at least having an option to show the derivation path (like `?fullpath=true`).

**Comment by pedroferreira1** [comment]
> Is it worth expanding this to return the derivation path? Or at least having an option to show the derivation path (like `?fullpath=true`).

I agree with you. We talked about returning only the index at first and expand later but I guess I can return a "hardcoded" full path for now and the lib will already be prepared if we allow different derivation paths later.
