### ISSUE TITLE
fix: Generate wallet using a derived xpub instead of a root xpub due to limitations on hardened derivation.

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-service-old#46]
The wallet service was expecting the root xpub, which was wrong because we can't derive a hardened path with a xpub.

We must change to receive the xpub in the last hardened path (account).

**Comment by msbrogli** [comment]
@pedroferreira1 I don't understand why we should do it.

Quick note: Even though the change is simple, it feels like a critical change that requires a lot of testing.

**Comment by jansegre** [comment]
As a user I'd rather send the most derived xpub rather than the root xpub. Because I could be using the same root xpub for other wallets even from other chains, sharing an xpub already gives up on some privacy, the root xpub gives up on that privacy for all wallets of that seed.
