### ISSUE TITLE
[Design] Update wallets in real time

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-service-old#50]
## Description

The client creates a websocket connection with the full node to receive some messages to handle real time updates in the wallet. After the integration with the wallet service, the wallet will need to receive this real time data from the service itself, it won't have a connection with the full node.

We will call 'client' the wallet-lib or any other wallet-service client. It's the one who will receive the updates in real time.

## How it is today

The wallets currently subscribe to two websocket messages:

1. `dashboard`: this message is important to get the network height and update the height locked balance.
2. `subscribe_address`: with this message, the wallet subscribes to receive updates from each address, then it receives any new transaction that spends an utxo of this address, or that creates an utxo of this address, or any transaction update, e.g. a tx becoming voided.

## How it will be

The wallet balance will be fully handled by the wallet service, then the wallet won't need to know anything about the network height. 

However when the wallet receives a new transaction (or an old tx is updated) we still need to show this change in real time.

Besides that, it's important that the ws client be prepared to receive a `force-full-reload` event, which could be used in case of a bug fix and we would like all clients to reload the data.

### Real time changes in the wallet

1. New transaction in the history
2. Balance update because of new utxo
3. Balance update because an old utxo was spent
4. A valid tx became voided (update history list and balance)
5. A voided tx became valid (update history list and balance)

#### New tx

**Event:** `new-tx` 
**Payload:**

```
{
	"tx_id": "00000117d49815a23a2741387b48b4704e0c93400cb29a7f80485959b08eef3b",
	"version": 0,
	"weight": 23.026284295752536,
	"timestamp": 1617896807,
	"is_voided": false,
	"inputs": [],
	"outputs": [{
		"value": 6400,
		"token_data": 0,
		"script": "dqkUtneiAsjMwg/3ZaeJ/+i3kw0zZCWIrA==",
		"decoded": {
			"type": "P2PKH",
			"address": "WfJqB5SNHnkwXCCGLMBVPcwuVr94hq1oKH",
			"timelock": null
		},
		"token": "00",
		"spent_by": null
	}],
	"parents": ["000000172502dfe765f74244038c3abba532d82c5bd7b51848fb80f0444b4398", "003e0c7595bd14271f9a0d7beda42e1781e278bc9a013e5a0c74fd186d999ebc", "007c446fcb0d696fa0b47cc4dd515ebd98d9538a01b20bcb0a7b08fefe890388"],
	"height": 651069,
	"is_block": true,
	"throttled": false // This indicates if there are other txs in the queue to be sent
}
```

#### Update tx

**Event:** `update-tx` 
**Payload:**

```
{
	"tx_id": "00000117d49815a23a2741387b48b4704e0c93400cb29a7f80485959b08eef3b",
	"is_voided": true
}
```

#### Force reload data

**Event:** `force-full-reload` 
**Payload:** No payload

## Implementation

- We will continue having a websocket connection to get the real time update from the wallet service.
- The wallet will subscribe with the wallet-id, then it's just one subscription to receive any real time update for that wallet.
- Every time a wallet-id receives a new tx, the service will send a ws message to all subscribed connections. Message 'new-tx' and the full tx data.
- Every time a wallet-id has an update of old tx, the service will send a ws message to all subscribed connections. Message 'update-tx' and the full tx data.
- When the wallet receives a ws message (`new-tx` or `update-tx`) it will query the wallet service for the balance of the tokens and will update the history with the data received (if it's showing the first page of the history)
- WS client must implement a `force-full-reload` method in case it receives this event. The WS server must be able to send this event.

## Tasks

We already have a websocket client in the lib that can be used.

1. Create a websocket server in the wallet service
2. The ws server must expect to receive `subscribe` and `ping` messages. We should reject any subscription for a wallet-id that does not exist in the service.
3. The ws server must store each connection for the wallet-id subscription.
4. When the connection is close the server must remove it from the list.
4. The ws server must send a `pong` message when it receives a `ping` message.
5. The ws server must send a `new-tx` or `update-tx` message to all subscribed connections of the transaction. You are related to the transaction if one of your addresses is either in the utxo list being spent of in the outputs list.
6. The wallet must update the tx history first page list in case of a `new-tx` message.
7. The wallet must query the balance for the token in case of a `new-tx` or `update-tx` message.
8. The wallet must update the status (voided/valid) of the transaction in the list in case of a `update-tx` message.
9. Method to fully reload the data in the client in case it receives a `force-full-reload` event. 

#### Total time

2 days

## Questions

1. Should we send in the `new-tx` message the final tx balance for each token, then we can update the wallet balance without needing to query? I decided not to do it because this is one of the reasons the wallet stops when it receives many transactions per second, updating the screen many times per second freezes the UI thread.
2. Should we continue updating the address to the next one when we receive an utxo for the 'current address'?

**Comment by msbrogli** [comment]
@pedroferreira1 I like the overall design and here are my initial thoughts.

1) I think we should call the "wallet-lib" or any other client of the wallet-service just  as "client", and we need to explain this at the beginning of the design.

1) I like the separation between `new-tx` and `update-tx` events since they have different impacts in the client, but I'd also create a `force-full-reload` event. It might be useful when a bug is fixed and we'd like to have all clients fully reloaded.

2) It would be great to have an example of each event and its payload. As far as I understood, `new-tx` will send all fields of the new transaction, while `update-tx` will send only the txid and metadata. Is it right?

3) I feel we should have a flow control by design to prevent a flood in the client. If the rate limit is exceeded we could use a `full-reload-when-possible` event so the client will do a full reload when it is possible.

4) I like the idea of piggybacking the balance in the `new-tx` and `update-tx` events is great. I feel the flow control (3) will prevent blocking the UI.

**Comment by pedroferreira1** [comment]
@msbrogli nice comments. From 1-3 agreed and changed in the text.

> 3. It would be great to have an example of each event and its payload. As far as I understood, `new-tx` will send all fields of the new transaction, while `update-tx` will send only the txid and metadata. Is it right?

I thought about returning only `tx_id` and `is_voided` in the `update-tx` event. What do you think?

> 4. I feel we should have a flow control by design to prevent a flood in the client. If the rate limit is exceeded we could use a `full-reload-when-possible` event so the client will do a full reload when it is possible.

I agree we should do it and started thinking about the limit. Even though it's nice to receive 10 txs/s, I don't see it as a normal use and the wallet UI would block the UI thread. I thought about limiting at 1 tx/s for each wallet, which seems enough and a good UI update. If the user receives more than this rate for a long time it will need to reload the data as soon as things gets normal. What do you think?

**Comment by andreabadesso** [comment]
I like the design, I just would like to see some more details on the implementation of the WebSocket server

In regards to your questions:

1) Even though I agree that it is bad to handle multiple messages per second when the client who is consuming the API is a smartphone, I believe would be limiting the potential uses for this WebSocket connection. I think it would be best to have a configuration parameter on the connection that tells the service how often it wants to receive messages. Maybe we can also add an env variable to configure the maximum frequency the wallet-service can broadcast. What do you think?

2) Maybe this could be configured per wallet?

**Comment by pedroferreira1** [comment]
> I like the design, I just would like to see some more details on the implementation of the WebSocket server
> 
> In regards to your questions:
> 
> 1. Even though I agree that it is bad to handle multiple messages per second when the client who is consuming the API is a smartphone, I believe would be limiting the potential uses for this WebSocket connection. I think it would be best to have a configuration parameter on the connection that tells the service how often it wants to receive messages. Maybe we can also add an env variable to configure the maximum frequency the wallet-service can broadcast. What do you think?
> 2. Maybe this could be configured per wallet?

I agree with both comments about the questions. Both could be configured in the wallets but I still feel it's critical that by default we have a rate limit for our wallets. It's not only smartphones that freeze with many (~3) txs/s, my desktop also freezes, so I feel it's important that we have this protection.

Regarding the WS server, another design will be created to handle the low level.

**Comment by pedroferreira1** [comment]
All pending decisions are from the low level, which will have another design to handle it, so I will close this one for now.
