### ISSUE TITLE
[Design] mempool sync

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-wallet-service-old#73]
# Summary
[summary]: #summary

Send transactions on the mempool (before they are confirmed by a block) to the wallet service to process.
They will be marked as mempool transactions and will be resent if a block is mined that confirm the transaction or if they are voided.
This change will include an api on the full-node to for downloading mempool transactions and new daemon states to download and process these transactions.

# Motivation
[motivation]: #motivation

### UX improvement
The transactions on the mempool are not being processed on the wallet service, so any transaction made by wallet clients will not show on balance until it is confirmed by a block.
If we have these transactions on the wallet service database we can show the clients the correct balance as soon as the balance recalculation is done, if the transaction is voided the next balance recalculation will correct the balance.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

Mempool is simply the group of transactions that have yet to be confirmed by a block.
This means that any transaction on the DAG that doesn't have a block as a child (directly or indirectly) is part of the mempool.

The full-node websocket api already sends any transaction to the daemon, but as of now only blocks are processed (this processess any tx confirmed by the block).
So we need to not ignore transactions if they are on the mempool and send a similar event to `NEW_BLOCK`, to enter a state to download mempool transactions and process them ("sync" mempool transactions).
To make this work we need a simple way to check if the transaction is on the mempool, the `tx.meta.first_block` metadata is perfect for this because it's the hash of the block that confirms the tx, so if this is not set the transaction is on the mempool.
Next we will need an api on the full-node to download all transactions on the mempool.

The order of operations then will be:
- A new transaction on the mempool arrives on the full-node and is sent to the daemon via websocket (observing transmission rates and time buffering).
- The daemon enters a `mempoolsync` state in which he will download the transactions on the mempool and pass them to the wallet service.
- The next state will be `idle` if finished processing the mempool or `syncing` (the block sync state) if a block has arrived while processing the mempool.
  - The block sync takes priority, so the mempool must stop mid-sync if a block arrives.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

## Full-node API

The api to download mempool transactions will return a list of mempool transaction ids sorted by the transaction timestamp and truncated at 100 transactions.
This api will return the same transactions even if the daemon already downloaded it on a previous attempt (provided the mempool hasn't changed), this way the burden of filtering mempool transactions will be on the daemon.

The full-node can (teoretically) handle a large number of transactions before a block comes to confirm these transactions, this means that the mempool can grow really large and in turn make this api return large responses, this could occupy resources such as network and cpu on the full-node, to limit this, we truncate the reponse to 100.

The reason why this api will only return the transaction id is because the consumer (daemon) needs information which could lead to more db searches (on the tx parents), so to minimize these searches, we return a list of transaction ids and the daemon can download each tx individually (this transaction api already makes the necessary db searches).

```json
{
  "/mempool": {
    "x-visibility": "public",
    "x-rate-limit": {
      "global": [
        {
          "rate": "50r/s",
          "burst": 100,
          "delay": 50
        }
      ],
      "per-ip": [
        {
          "rate": "3r/s",
          "burst": 10,
          "delay": 3
        }
      ]
    },
    "get": {
      "tags": ["mempool"],
      "operationId": "mempool",
      "summary": "List of mempool transactions",
      "description": "Returns a list of all transactions currently on the mempool",
      "responses": {
        "200": {
          "description": "Success",
          "content": {
            "application/json": {
              "examples": {
                "success": {
                  "summary": "Success",
                  "value": {
                    "success": true,
                    "transactions": [
                      "339f47da87435842b0b1b528ecd9eac2495ce983b3e9c923a37e1befbe12c792",
                      "16ba3dbe424c443e571b00840ca54b9ff4cff467e10b6a15536e718e2008f952",
                      "33e14cb555a96967841dcbe0f95e9eab5810481d01de8f4f73afb8cce365e869"
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Implemented on [#241](https://github.com/HathorNetwork/hathor-core/pull/241).

## Daemon states

The new `mempoolsync` state will be triggered if any transaction on the mempool arrives on the websocket connection (a signal that the mempool has changed), If the machines arrives at the `idle` state and and the `hasMempoolUpdate` boolean is `true` it enters the `mempoolsync` state much like the block sync boolean `hasMoreBlocks`, but the preference is for block sync so if both are set, the block sync will be tested first and the block sync will start.

Once in `mempoolsync` state we will execute these steps:

1. Call the mempool api on the full-node receiving a list of tx ids on the mempool.
2. Download the full tx from the full-node transaction api using the tx id
3. Send the full-tx to the wallet-service.

The steps `2` and `3` will repeat for each tx on the list. During this execution, if a block arrives, the machine will exit this `mempoolsync` state and the execution will stop after the next step `3` (it will finish the last step `3` because of how promises work on js).

If the execution stops before finishing, the boolean `hasMempoolUpdate` will be set to `true` so that when the machine reaches the next `idle` state it automatically goes back to `mempoolsync`.

The state machine diagram can be visualized [here](https://xstate.js.org/viz/?gist=19dd8bc6d62533add23e124ef31adb78)

Implemented on [#11](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/pull/11).

## Wallet Service

No need to update wallet service for handling mempool transactions, the wallet is already ready to process mempool transactions.
They are saved on the same database as confirmed transactions and marked with `height=null`.

* Transactions do not have height, but on the wallet-service they are marked with the height of the first block that confirms the transaction (This is why `height=null` means the transaction is on the mempool).
* Maybe port this behavior to hathor-core.

**Comment by msbrogli** [comment]
Initial comments:

1) I feel the summary is touching in a technical detail of the mempool sync (instead of a summary of what it does).

2) I'm missing the Motivation section where we explain why it is relevant.

3) I feel that we can use the same old `transaction` table with an additional boolean flag `mempool`. This way all balance calculation algorithms works without any change. Maybe we'll need another boolean flag `voided` that might impact these algorithms.

4) This design needs to explain how the wallet service updates the transactions in the mempool. I feel we can add an API in the full-node that streams the transactions in topological order to the wallet service. This approach guarantees that all dependencies are met and solves the "out of order" issue. Even though it might not be efficient, the mempool is usually small enough to work fine, and we might improve it later when needed.

5) Besides the mechanism behind the mempool sync, I think the sync should both (i) run periodically, and (ii) subscribe to receive real-time updates from the full-node. While the real-time subscription will ensure fast update to the wallets when a new transaction arrives, the periodical sync will fix eventual problems that might arrive from the real-time events.

**Comment by pedroferreira1** [comment]
I like the design, I think we can reference here the PRs that implemented the design in the text. We have the daemon PR, the full node API PR and the wallet service PR as well, right?

> If we have these transactions on the wallet service database we can show the clients this balance as "locked" or "waiting confirmation" as soon as the balance recalculation is done and add to balance once it's confirmed.

The balance of mempool transactions should be shown as normal balances.

> Transactions do not have height, but on the wallet-lib they are marked with the height of the first block that confirms the transaction (This is why height=null means the transaction is on the mempool).

You mean the 'wallet-service' instead of 'wallet-lib', right?

**Comment by andreabadesso** [comment]
I know that it is implicit on the text that we are pausing the mempool sync when a `NEW_BLOCK` event arrives to try our best to guarantee that all dependencies will be met, but I think we can be clearer about this on the text so someone that reads it on the design will understand it faster.

Maybe also add an explanation on how the wallet service confirms the mempool transactions on its database

> The daemon enters a mempoolsync state in which he will download the transactions on the mempool and pass them to the wallet service.

I think that here we should point out that we are downloading the entire list of mempool transactions from the full-node and that it is truncated to 150(?) transactions and maybe that will be a problem if we have a higher number of transactions on the mempool

**Comment by msbrogli** [comment]
I think the design is not covering the different cases that might happen, including the prioritization of blocks if a new block is found while the sync is running.

We also must explain why we are downloading all transactions in the mempool at once and that it might be a problem if the mempool gets too big. In this case, how would this sync fail? Run out of memory? Too slow? Or would it miss some transactions?

**Comment by pedroferreira1** [comment]
The design is approved for me.

@r4mmer I think only the following comment @msbrogli did is not answered in the design:

> In this case, how would this sync fail? Run out of memory? Too slow? Or would it miss some transactions?

**Comment by andreabadesso** [comment]
The design is approved for me

**Comment by r4mmer** [comment]
> The full-node can (teoretically) handle a large number of transactions before a block comes to confirm these transactions, this means that the mempool can grow really large and in turn make this api return large responses, this could occupy resources such as network and cpu on the full-node, to limit this, we truncate the reponse to 100.

This covers why we decided on truncating the api response, the response being truncated is the solution when the mempool grows too large. This means we can miss transactions when the mempool grows over 100 (but we will get them on the block sync when they're confirmed).

> If the execution stops before finishing, the boolean `hasMempoolUpdate` will be set to `true` so that when the machine reaches the next `idle` state it automatically goes back to `mempoolsync`.

The mempool download can be too slow, specially since we download each tx individually, there is no mapped solution to this, but if the mempool sync gets too slow the next block sync will stop this sync and start another mempool sync after.

The case of running out of memory would be implicit on the truncated api response, because the list of tx ids could grow large, increasing with it the resources needed, but since the list has a limit, the resources needed also have a limit.
