### ISSUE TITLE
[Design - old] Sync with the full-node

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-service-old#8]
# !!! This issue has been replaced with https://github.com/HathorNetwork/hathor-wallet-service/issues/35, all design discussions should be continued there !!!

This design details the sync between the service and the full node. This part is missing in the general design (https://github.com/HathorNetwork/hathor-wallet-service/issues/1).

## Proposal (unfinished)

The sync can be done keeping track of the latest block `B` that the service has seen. So, when the service restarts, it searches for that block and sync with all blocks after it. We still need to handle some special cases.

When initializing the sync, the first block can be either executed or voided.

(i) If `B` is executed, we just need to go from that block to the head of the best blockchain in the full node.

(ii) If `B` is voided, we need go to back until we reach the best blockchain again. Let's say it is block `X`. Then, we move forward from `X` to the head of the best blockchain. All transactions between `B` and `X` must be checked because they may have been voided.

After the blocks have been synced, we need to go through all unverified transactions.

### Transactions verified by a block

We can use the first_block metadata to easily identify all transactions which were firstly verified by a given block. We basically run a BFS that stops adding to the queue when first_block != block.

### Unverified transactions

We can run a BFS starting with the tips and that stops adding to the queue when first_block is not empty.

## Pending Decisions

1) Should we sync voided blocks and transactions?

We may sync all voided blocks. I'm not sure if it should be optional. If we don't do it, users won't see their voided blocks in their wallets. If we want to do it, we can keep track of the head of all non-best blockchains, but it may grow over time.

If we decide that we must have all blocks and transactions, including the voided ones, we can really sync all blocks and transactions. But I'm not sure it is the best strategy for the wallet.

**Comment by msbrogli** [comment]
The sync can be done keeping track of the latest block `B` that the service has seen. So, when the service restarts, it searches for that block and sync with all blocks after it. We still need to handle some special cases.

When initializing the sync, the first block can be either executed or voided.

(i) If `B` is executed, we just need to go from that block to the head of the best blockchain in the full node.

(ii) If `B` is voided, we need go to back until we reach the best blockchain again. Let's say it is block `X`. Then, we move forward from `X` to the head of the best blockchain. All transactions between `B` and `X` must be checked because they may have been voided.

After the blocks have been synced, we may need to go through all unverified transactions.

We may sync all voided blocks. I'm not sure if it should be optional. If we don't do it, users won't see their voided blocks in their wallets. If we want to do it, we can keep track of the head of all non-best blockchains, but it may grow over time.

If we decide that we must have all blocks and transactions, including the voided ones, we can really sync all blocks and transactions. But I'm not sure it is the best strategy for the wallet.

@obiyankenobi @jansegre @pedroferreira1 What do you think?

**Comment by obiyankenobi** [comment]
I think it's a good strategy for the blocks, but the most complex part are the transactions. 

Do we already have some easy way to get all transactions "after" a given block? By "after", I mean that are not confirmed (directly or indirectly) by the block, not considering the timestamp.

**Comment by msbrogli** [comment]
> Do we already have some easy way to get all transactions "after" a given block? By "after", I mean that are not confirmed (directly or indirectly) by the block, not considering the timestamp.

For blocks in the best blockchain, we do. We can use the `first_block` metadata to easily identify all transactions which were firstly verified by a given block. We basically run a BFS that stops adding to the queue when `first_block != block`.

**Comment by jansegre** [comment]
It seems like a good strategy. There are other things I'd like to improve on the sync protocol. Should we make an RFC to discuss a new "sync v2" protocol? The wallet service would be the pilot test for the sync v2, and when we're happy with it we can start rolling it out for the networks P2P.

**Comment by pedroferreira1** [comment]
I think it's a good strategy, seems to work for what we want.

> Should we sync voided blocks and transactions?

I think wallets should be able to show voided blocks, we can discuss UI later but if a user sees a block in his wallet and then it disappears, he should be able to see that this block was actually voided.
